#!/usr/bin/env bash
# =============================================================================
# scripts/checks/counts.sh — the numbers in the prose match the numbers in the code
#
# Purpose:  Three places claimed three different sizes for the same repo: the
#           GitHub description said 41 checks and a 100-tool inventory, the
#           README said 42 and 102, the app said 42 and 103. Every one of them
#           had been true once. None of them was checked.
#
#           A repo whose entire argument is "drift becomes visible" cannot let
#           its own headline numbers drift. So: one generated source
#           (manifests/counts.json), everything else reads from it, and this
#           check recounts from the code and fails when prose and code disagree.
#
#           What is counted, and from where:
#             doctor_checks   TOTAL_CHECKS in doctor.sh
#             registry_tools  entries in manifests/tools.yaml — the PUBLIC file
#                             only. local/manifests/tools.local.yaml is one
#                             machine's overlay and must never move a published
#                             number.
#             gate_checks     entries in the CHECKS list in scripts/gate.sh
#             setup_modules   numbered modules scripts/00-*.sh .. scripts/11-*.sh
#                             (12-first-light and 90-cleanup are named separately
#                             everywhere, because neither is part of a level)
#             automation_cmds files in automation/bin/
#
# Changes:  Nothing, unless called with --write.
# Usage:    scripts/checks/counts.sh [--write] [--help]
#
#   --write   regenerate manifests/counts.json from the code (the only mode
#             that writes; run it after adding a check or a tool)
# =============================================================================
set -uo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

WRITE=0
case "${1:-}" in
    -h | --help)
        sed -n '2,27p' "${BASH_SOURCE[0]}"
        exit 0
        ;;
    --write) WRITE=1 ;;
    "") ;;
    *)
        printf 'unknown option: %s\n' "$1" >&2
        exit 2
        ;;
esac

require yq

COUNTS_JSON="manifests/counts.json"

# --- count from the code -----------------------------------------------------
doctor_checks="$(sed -nE 's/^TOTAL_CHECKS=([0-9]+).*/\1/p' doctor.sh | head -1)"
registry_tools="$(yq e 'length' manifests/tools.yaml 2>/dev/null)"
gate_checks="$(sed -n '/^CHECKS="$/,/^"$/p' scripts/gate.sh | grep -c '\.sh$')"
# Globs, not `ls | grep`: a filename with a space would silently miscount, and
# the gate's own shellcheck refuses the pipe form anyway.
count_glob() {
    n=0
    for f in "$@"; do
        [ -e "$f" ] && n=$((n + 1))
    done
    printf '%s\n' "$n"
}
setup_modules="$(count_glob scripts/0[0-9]-*.sh scripts/1[01]-*.sh)"
automation_cmds="$(count_glob automation/bin/*)"

for pair in "doctor_checks:$doctor_checks" "registry_tools:$registry_tools" \
    "gate_checks:$gate_checks" "setup_modules:$setup_modules" \
    "automation_cmds:$automation_cmds"; do
    name="${pair%%:*}"
    value="${pair#*:}"
    if ! printf '%s' "$value" | grep -qE '^[0-9]+$' || [ "$value" -eq 0 ]; then
        violation "could not count $name (got '$value') — the source moved, fix this check"
        exit 1
    fi
done

render_json() {
    cat <<EOF
{
  "_comment": "Generated by scripts/checks/counts.sh --write. Do not edit by hand.",
  "_sources": {
    "doctor_checks": "TOTAL_CHECKS in doctor.sh",
    "registry_tools": "entries in manifests/tools.yaml (public file only)",
    "gate_checks": "entries in the CHECKS list in scripts/gate.sh",
    "setup_modules": "scripts/00-*.sh through scripts/11-*.sh",
    "automation_cmds": "files in automation/bin/"
  },
  "doctor_checks": $doctor_checks,
  "registry_tools": $registry_tools,
  "gate_checks": $gate_checks,
  "setup_modules": $setup_modules,
  "automation_cmds": $automation_cmds
}
EOF
}

if [ "$WRITE" = 1 ]; then
    render_json > "$COUNTS_JSON"
    printf 'wrote %s: %s checks, %s tools, %s gate checks, %s modules, %s commands\n' \
        "$COUNTS_JSON" "$doctor_checks" "$registry_tools" "$gate_checks" \
        "$setup_modules" "$automation_cmds"
    exit 0
fi

fail=0

# --- 1. counts.json agrees with a fresh count --------------------------------
if [ ! -f "$COUNTS_JSON" ]; then
    violation "$COUNTS_JSON is missing — generate it with scripts/checks/counts.sh --write"
    exit 1
fi

if ! diff -q <(render_json) "$COUNTS_JSON" >/dev/null 2>&1; then
    violation "$COUNTS_JSON is stale"
    diff <(render_json) "$COUNTS_JSON" | sed 's/^/    /' >&2
    printf '  regenerate with: scripts/checks/counts.sh --write\n' >&2
    fail=1
fi

# --- 2. the prose agrees with the count --------------------------------------
# Tracked English documentation only. docs/de/ is a frozen archive that is
# deliberately not kept in sync (BIBLE decision), and reviews quote numbers as
# they stood on the day of the review — both would be false positives.
doc_files="$(git ls-files -- '*.md' \
    ':(exclude)docs/de/*' \
    ':(exclude)docs/reviews/*' \
    ':(exclude)CHANGELOG.md' \
    ':(exclude)HANDOFF.md' 2>/dev/null)"

check_claims() {
    local pattern="$1" expected="$2" label="$3"
    local hits
    hits="$(printf '%s\n' "$doc_files" | tr '\n' '\0' \
        | xargs -0 grep -nE "[0-9]+ $pattern" 2>/dev/null \
        | grep -vE "\b$expected $pattern" || true)"
    [ -z "$hits" ] && return 0
    violation "documentation claims a $label count that is not $expected"
    printf '%s\n' "$hits" | sed 's/^/    /' >&2
    fail=1
}

check_claims "checks" "$doctor_checks" "doctor check"
check_claims "tools" "$registry_tools" "registry tool"
check_claims "(numbered )?modules" "$setup_modules" "setup module"
check_claims "commands" "$automation_cmds" "automation command"

if [ "$fail" -eq 1 ]; then
    exit 1
fi

note "counts consistent ($doctor_checks checks, $registry_tools tools, $setup_modules modules, $automation_cmds commands)"
exit 0
